#!/bin/bash
_CURRENT_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
_CURRENT_RUNNING_DIR="$( cd "$( dirname "." )" && pwd )"

STELLA_LOG_STATE="OFF"
. "${_CURRENT_FILE_DIR}/stella-link.sh" include

. "${_CURRENT_FILE_DIR}/lib/lib.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_json.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_yaml.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_node.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_cpa.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_vscode.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_gemini.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_opencode.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_kilo.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_orla.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_mcp.sh"

# --- USAGE ---
usage() {
    cat << EOF
AIStack CLI

Usage: aistack [options]

Options:
    init                    Install/Reinstall dependencies.
    uninstall               Uninstall aistack, all tools, mcp servers and unregister everything from PATH.
    help                    Display this help message.
    shell                   Enter aistack context and path.
    ----
    gc : gemini-cli - https://google-gemini.github.io/gemini-cli
    gc install [@version]           Install and configure Gemini CLI. (main versions are latest, nightly, preview) (when asked to relaunch gemini cli, use 'aistack gc launch' command)
    gc uninstall                    Uninstalling Gemini CLI and unregister Gemini CLI PATH (keep all configuration unchanged, to remove configuration use 'aistack gc reset' command)
    gc configure                    Configure Gemini CLI. ('aistack gc install' include configuration)
    gc show-config                  Show current Gemini CLI configuration.
    gc reset                        Reset all Gemini CLI configuration.
    gc register <shell>|vs          Register Gemini CLI PATH into shell env PATH ("bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs")
    gc unregister <shell>|vs        Unregister Gemini CLI PATH into shell env PATH ("bash", "zsh", "fish" or "all") or into VS Code integrated terminal env PATH ("vs")
    gc launch [context folder] -- <other gemini options>                  
                                    Launch Gemini CLI. Instead use 'gemini' command if ${AISTACK_GEMINI_LAUNCHER_HOME} is in your PATH,
                                    you could use 'aistack gc register <shell>'
    gc set <key> <value>            Set a Gemini CLI configuration in settings file.
    gc del <key>                    Delete a Gemini CLI configuration in settings file.
    gc mcp calculator install|uninstall         Add mcp-calculator local server configuration.
    gc mcp github install|uninstall             Add mcp-github remote server configuration.
    gc mcp desktop-commander install|uninstall  Add mcp-desktop-commander local server configuration.
    gc mcp context7 install|uninstall   [CONTEXT7_API_KEY]        Add mcp-context7 local server configuration. Provide optional CONTEXT7_API_KEY as environment variable or command argument.
    gc mcp data commons install|uninstall [DC_API_KEY]          Add mcp-data-commons remote server configuration. Provide mandatory DC_API_KEY from https://apikeys.datacommons.org/ as environment variable or command argument.
    ----
    oc : opencode - https://opencode.ai
    oc install                          Install and configure Opencode.
    oc uninstall                        Uninstall Opencode and unregister Opencode PATH (keep all configuration unchanged, to remove configuration use 'aistack oc reset' command)
    oc configure                        Configure Opencode. ('aistack oc install' include configuration)
    oc show-config                      Show current Opencode configuration.
    oc reset                            Reset all Opencode configuration.
    oc register <shell>|vs              Register Opencode PATH into shell env PATH ("bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs")
    oc unregister <shell>|vs            Unregister Opencode PATH into shell env PATH ("bash", "zsh", "fish" or "all") or into VS Code integrated terminal env PATH ("vs")
    oc launch [context folder] -- <other opencode options>
                                        Launch Opencode. Instead use 'opencode' command if ${AISTACK_OPENCODE_LAUNCHER_HOME} is in your PATH,
                                        you could use 'aistack oc register <shell>'
    oc mcp calculator install|uninstall         Add mcp-calculator local server configuration.
    oc mcp github install|uninstall             Add mcp-github remote server configuration.
    oc mcp context7 install|uninstall           Add mcp-context7 local server configuration.
    ----
    kc : Kilo Code CLI and VS Code extension - https://kilo.ai/
    kc install                          Install and configure Kilo Code.
    kc uninstall                        Uninstall Kilo Code and unregister Kilo Code PATH (keep all configuration unchanged, to remove configuration use 'aistack kc reset' command)
    kc configure                        Configure Kilo Code. ('aistack kc install' include configuration)
    kc info                             Print Kilo Code informations.
    kc show-config                      Show current Kilo Code configuration.
    kc reset                            Reset all Kilo Code configuration.
    kc register <shell>|vs              Register Kilo Code PATH into shell env PATH ("bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs")
    kc unregister <shell>|vs            Unregister Kilo Code PATH into shell env PATH ("bash", "zsh", "fish" or "all") or into VS Code integrated terminal env PATH ("vs")
    kc launch [context folder] -- <other kilo code options>
                                        Launch Kilo Code. Instead use 'kilo' command if ${AISTACK_KILO_LAUNCHER_HOME} is in your PATH,
                                        you could use 'aistack kc register <shell>'
    kc connect cpa                      Connect Kilo Code CLI and VS Code extension to CLIProxyAPI. (require 'aistack cpa install' before)
    ----
    vs set <key> <value>                Set a VS Code configuration in settings file.
    vs del <key>                        Delete a VS Code configuration in settings file.
    vs info                             Print VSCode informations.
    vs show-config                      Show current VSCode configuration.
    ----
    orla : Orla - https://github.com/dorcha-inc/orla
    orla install                      Install and configure Orla.
    orla uninstall                    Uninstalling Orla and unregister Orla PATH (keep all configuration unchanged, to remove configuration use 'aistack gc reset' command)
    orla configure                    Configure Orla. ('aistack orla install' include configuration)
    orla info                         Print Orla informations.
    orla show-config                  Show current Orla configuration.
    orla reset                        Reset all Orla configuration.
    orla register <shell>|vs          Register Orla PATH into shell env PATH ("bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs")
    orla unregister <shell>|vs        Unregister Orla PATH into shell env PATH ("bash", "zsh", "fish" or "all") or into VS Code integrated terminal env PATH ("vs")
    orla agent <other Orla options>   Execute Orla agent command. (i.e: aistack orla agent "Hello world" -m "gemini-2.5-flash")
    orla serve <other Orla options>   Execute Orla serve command - Launch Orla API service.
    orla launch [context folder] -- <other Orla options>                  
                                      Launch Orla. Instead use 'orla' command if ${AISTACK_ORLA_LAUNCHER_HOME} is in your PATH,
                                      you could use 'aistack orla register <shell>'
    orla set <key> <value> ["string"]     Set a Orla key in setting file. (i.e: cpa set listen_address localhost:8081) Use optional "string" option if value is a string.
    orla get <key>                        Get a Orla key from setting file. (i.e: cpa get api-key.0)
    orla connect agent|serve cpa [<model>]                      Connect Orla agent or service mode to CLIProxyAPI. By default will set the first model from CLIProxyAPI as the default model. You can provide a specific model.
    ----
    cpa : CLIProxyAPI - https://github.com/router-for-me/CLIProxyAPI
    cpa install                          Install and configure CLIProxyAPI.
    cpa uninstall                        Uninstall CLIProxyAPI (keeping all configuration unchanged. to remove configuration use 'aistack cpa reset' command)
    cpa configure                        Configure CLIProxyAPI. ('aistack cpa install' include configuration)
    cpa info                             Print CLIProxyAPI informations.
    cpa show-config                      Show current CLIProxyAPI configuration.
    cpa reset                            Reset all CLIProxyAPI configuration.
    cpa launch [context folder] -- <other CLIProxyAPI options>                   Launch CLIProxyAPI.
    cpa login gemini-oauth [--project_id <your_project_id>]                     Login to Gemini OAuth.
    cpa login openai-oauth               Login to OpenAI OAuth.
    cpa login qwen-oauth                 Login to Qwen OAuth.
    cpa set <key> <value> ["string"]     Set a CLIProxyAPI key in setting file. (i.e: cpa set port 8000) Use optional "string" if option value is a string.
    cpa get <key>                        Get a CLIProxyAPI key from setting file. (i.e: cpa get api-key.0)
    cpa key generate                     Generate a new API key for CLIProxyAPI and add it to the configuration.
    cpa key list                         List all API keys from CLIProxyAPI configuration.
    cpa key get <N>                      Get API key N. (i.e: cpa key get 0)
    cpa key reset                        Remove all API keys from CLIProxyAPI configuration.
    cpa key delete <key>                 Remove an API key from CLIProxyAPI configuration.
    cpa model list                       List all available LLM models from CLIProxyAPI endpoint.
    ----
    npm-config set <key> <value>         Set a npm configuration for the internal nodejs.
    ----
    app killport <port>                  Kill process running on a specific port.
    ----
EOF
}


# Main function
main() {
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        usage
        exit 0
    fi

    if [ "$#" -eq 0 ]; then
        usage
        exit 1
    fi

    local command="$1"
    shift
    case "$command" in
        help)
            usage
            exit 0
            ;;
        shell)
            $STELLA_API boot_app_shell "local"
            ;;
        init)
            aistack_init
            ;;
        uninstall)
            aistack_uninstall
            ;;
        npm-config)
            if ! check_requirements "nodejs"; then echo " -- ERROR : nodejs missing, launch aistack init"; exit 1; fi;
            local sub_command="$1"
            shift
            case "$sub_command" in
                set)
                    local key="$1"
                    shift
                    local value="$1"
                    shift
                    if [ -z "$key" ]; then
                        echo " -- ERROR : Missing key for npm-config set"
                        usage
                        exit 1
                    fi
                    echo "Setting npm config: $key = $value"
                    PATH="${AISTACK_NODEJS_BIN_PATH}:${PATH}" npm config set "$key" "$value" -g
                    ;;
                *)
                    echo "Error: Unknown command $sub_command for npm-config"
                    usage
                    exit 1
                    ;;
            esac
            ;;
        app)
            local sub_command="$1"
            shift
            case "$sub_command" in
                killport)
                    local port="$1"
                    shift
                    if [ -z "$port" ]; then
                        echo " -- ERROR : Missing port for app killport"
                        usage
                        exit 1
                    fi
                    process_kill_by_port "$port"
                    ;;
                *)
                    echo "Error: Unknown command $sub_command for app"
                    usage
                    exit 1
                    ;;
            esac
            ;;
        oc)
            . "${_CURRENT_FILE_DIR}/lib/main_oc.sh"
            ;;
        gc)
            . "${_CURRENT_FILE_DIR}/lib/main_gc.sh"
            ;;
        cpa)
            . "${_CURRENT_FILE_DIR}/lib/main_cpa.sh"
            ;;
        vs)
            . "${_CURRENT_FILE_DIR}/lib/main_vs.sh"
            ;;
        orla)
            . "${_CURRENT_FILE_DIR}/lib/main_orla.sh"
            ;;
        kc)
            . "${_CURRENT_FILE_DIR}/lib/main_kilo.sh"
            ;;
        *)
            echo "Error: Unknown command $command"
            usage
            exit 1
            ;;
    esac

    
}


aistack_path
runtime_path


main "$@"
