#!/bin/bash
_CURRENT_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
_CURRENT_RUNNING_DIR="$( cd "$( dirname "." )" && pwd )"

STELLA_LOG_STATE="OFF"
. "${_CURRENT_FILE_DIR}/stella-link.sh" include

# NOTE
#   From HERE, $STELLA_ORIGINAL_SYSTEM_PATH contains $PATH before stella features are included

. "${_CURRENT_FILE_DIR}/lib/lib.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_json.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_yaml.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_node.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_bun.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_agy.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_cpa.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_vscode.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_gemini.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_opencode.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_kilo.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_orla.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_bmad.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_gsd.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_adk.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_asm.sh"
. "${_CURRENT_FILE_DIR}/lib/lib_mcp.sh"

# --- USAGE ---
usage() {
    cat << EOF
AIStack CLI

Usage: aistack [options]

Options:
    init                    Install/Reinstall dependencies.
    uninstall               Uninstall AIStack, all tools, mcp servers and unregister everything from PATH.
    help                    Display this help message.
    info                    Display various aistack information and configuration.
    shell                   Enter aistack AIStack and path.
	runtime add|remove <runtime> Install/remove an AIStack managed runtime to be used in any tool run context (Available: $AISTACK_RUNTIME). Core runtimes are always preinstalled ($AISTACK_RUNTIME_CORE)
    ----
    gc : gemini-cli - https://google-gemini.github.io/gemini-cli
    gc install [@version]           Install and configure Gemini CLI. (main versions are latest, nightly, preview) (when asked to relaunch gemini cli, use 'aistack gc launch' command)
    gc uninstall                    Uninstalling Gemini CLI and unregister Gemini CLI PATH. (keep all configuration unchanged, to remove configuration use 'aistack gc reset' command)
    gc configure                    Configure Gemini CLI with some default values. But do not fully reset all other existing config values. ('aistack gc install' include configuration)
    gc info                         Print Gemini CLI informations.
    gc show-config                  Show current Gemini CLI configuration.
    gc reset                        Reset all Gemini CLI configuration.
    gc register <all|shell|vs>      Register Gemini CLI PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs").
    gc unregister [<all|shell|vs>]  Unregister Gemini CLI PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs"). Default value is "all".
    gc launch [context folder] -- <gemini cli command>                  
                                    Launch Gemini CLI. Instead use 'gemini' command if ${AISTACK_GEMINI_LAUNCHER_HOME} is in your PATH.
                                    Use 'aistack gc register <shell>' to set it in your PATH.
    gc set <key> <value>            Set a Gemini CLI configuration in settings file.
    gc del <key>                    Delete a Gemini CLI configuration in settings file.
    gc mcp calculator install|uninstall         Add mcp-calculator local server configuration.
    gc mcp github install|uninstall             Add mcp-github remote server configuration.
    gc mcp desktop-commander install|uninstall  Add mcp-desktop-commander local server configuration.
    gc mcp context7 install|uninstall   [CONTEXT7_API_KEY]        Add mcp-context7 local server configuration. Provide optional CONTEXT7_API_KEY as environment variable or command argument.
    gc mcp data commons install|uninstall [DC_API_KEY]          Add mcp-data-commons remote server configuration. Provide mandatory DC_API_KEY from https://apikeys.datacommons.org/ as environment variable or command argument.
    ----
    oc : opencode - https://opencode.ai
    oc install                          Install and configure Opencode.
    oc uninstall                        Uninstall Opencode and unregister Opencode PATH (keep all configuration unchanged, to remove configuration use 'aistack oc reset' command)
    oc configure                        Configure Opencode with some default values. But do not fully reset all other existing config values. ('aistack oc install' include configuration)
    oc info                             Print Opencode informations.
    oc show-config                      Show current Opencode configuration.
    oc reset                            Reset all Opencode configuration.
    oc register <all|shell|vs>          Register Opencode PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs").
    oc unregister [<all|shell|vs>]      Unregister Opencode PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs"). Default value is "all".
    oc launch [context folder] -- <opencode command>
                                        Launch Opencode. Instead use 'opencode' command if ${AISTACK_OPENCODE_LAUNCHER_HOME} is in your PATH.
                                        Use 'aistack oc register <shell>' to set it in your PATH.
    oc connect cpa [<model>]            Connect Opencode to CLIProxyAPI using OpenAI-compatible provider. By default registers all models and sets the first as default. <model> provide a specific model.
    oc mcp calculator install|uninstall         Add mcp-calculator local server configuration.
    oc mcp github install|uninstall             Add mcp-github remote server configuration.
    oc mcp context7 install|uninstall           Add mcp-context7 local server configuration.
    ----
    kc : Kilo Code CLI and VS Code extension - https://kilo.ai/
    kc install [cli|extension]          Install and configure Kilo Code. By default, installs the CLI.
    kc uninstall [cli|extension]        Uninstall Kilo Code and unregister Kilo Code PATH. (keep all configuration unchanged, to remove configuration use 'aistack kc reset' command)
    kc configure                        Configure Kilo Code with some default values. But do not fully reset all other existing config values. ('aistack kc install' include configuration)
    kc info                             Print Kilo Code informations.
    kc show-config                      Show current Kilo Code configuration.
    kc reset                            Reset all Kilo Code configuration.
    kc register <all|shell|vs>          Register Kilo Code PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs").
    kc unregister [<all|shell|vs>]      Unregister Kilo Code PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs"). Default value is "all".
    kc launch [context folder] -- <other kilo code options>
                                        Launch Kilo Code. Instead use 'kilo' command if ${AISTACK_KILO_LAUNCHER_HOME} is in your PATH.
                                        Use 'aistack kc register <shell>' to set it in your PATH.
    kc connect cpa [<model>]            Connect Kilo Code CLI and VS Code extension to CLIProxyAPI. Create a CLIProxyAPI provider and register all models into Kilo Code and sets the first as default. <model> provide a specific model. Require 'aistack cpa launch'.
    ----
    orla : Orla - https://github.com/dorcha-inc/orla
    orla install                      Install and configure Orla.
    orla uninstall                    Uninstalling Orla and unregister Orla PATH. (keep all configuration unchanged, to remove configuration use 'aistack orla reset' command)
    orla configure                    Configure Orla with some default values. But do not fully reset all other existing config values. ('aistack orla install' include configuration)
    orla info                         Print Orla informations.
    orla show-config                  Show current Orla configuration.
    orla reset                        Reset all Orla configuration.
    orla register <all|shell|vs>      Register Orla PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs").
    orla unregister [<all|shell|vs>]  Unregister Orla PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs"). Default value is "all".
    orla agent <other orla options>   Execute Orla agent command. (i.e: aistack orla agent "Hello world" -m "gemini-2.5-flash")
    orla serve <other orla options>   Execute Orla serve command - Launch Orla API service.
    orla launch [context folder] -- <Orla command>                  
                                      Launch Orla. Instead use 'orla' command if ${AISTACK_ORLA_LAUNCHER_HOME} is in your PATH.
                                      Use 'aistack orla register <shell>' to set it in your PATH.
    orla set <key> <value> ["string"]     Set a Orla key in setting file. (i.e: cpa set listen_address localhost:8081) Use optional "string" option if value is a string.
    orla get <key>                        Get a Orla key from setting file. (i.e: cpa get api-key.0)
    orla connect agent|serve cpa [<model>]                      Connect Orla agent or service mode to CLIProxyAPI. By default will set the first model from CLIProxyAPI as the default model. <model> provide a specific model.
    ----
    cpa : CLIProxyAPI - https://github.com/router-for-me/CLIProxyAPI
    cpa install                          Install and configure CLIProxyAPI.
    cpa uninstall                        Uninstall CLIProxyAPI. (keeping all configuration unchanged. to remove configuration use 'aistack cpa reset' command)
    cpa configure                        Configure CLIProxyAPI with some default values. Erase all existing API keys but do not fully reset all other existing config values. ('aistack cpa install' include configuration)
    cpa info                             Print CLIProxyAPI informations.
    cpa show-config                      Show current CLIProxyAPI configuration.
    cpa reset                            Reset all CLIProxyAPI configuration.
    cpa launch [context folder] -- <CLIProxyAPI command>                   Launch CLIProxyAPI.
    cpa login agy-oauth [--project_id <your_project_id>]                     Login to Antigravity OAuth.
    cpa login codex-oauth                Login to Codex OAuth (OpenAI).
    cpa login kimi-oauth                 Login to Kimi OAuth.
	cpa login claude-oauth                 Login to Claude OAuth (Anthropic)
    cpa set <config key> <value> ["string"]     Set a CLIProxyAPI key in setting file. (i.e: cpa set port 8000) Use optional "string" if option value is a string.
    cpa get <config key>                 Get a CLIProxyAPI key from setting file. (i.e: cpa get api-key.0)
    cpa key generate                     Generate a new API key for CLIProxyAPI and add it to the configuration. (cpa must be installed before)
    cpa key list                         List all API keys from CLIProxyAPI configuration.
    cpa key get <N>                      Get API key N. (i.e: cpa key get 0)
    cpa key reset                        Remove all API keys from CLIProxyAPI configuration.
    cpa key delete <key>                 Remove an API key from CLIProxyAPI configuration. (cpa must be installed before)
    cpa model list                       List all available LLM models from CLIProxyAPI endpoint.
    ----
    agy : Antigravity CLI - https://antigravity.google/
    agy install [latest]                Install Antigravity CLI.
    agy uninstall                       Uninstall Antigravity CLI and unregister Antigravity CLI PATH.
    agy configure                    	Configure Antigravity CLI with some default values. But do not fully reset all other existing config values. ('aistack agy install' include configuration)
	agy info                            Print Antigravity CLI informations.
    agy show-config                  	Show current Antigravity CLI  configuration.
    agy reset                       	Reset all Antigravity CLI configuration.
	agy register <all|shell|vs>         Register Antigravity CLI PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs").
    agy unregister [<all|shell|vs>]     Unregister Antigravity CLI PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs"). Default value is "all".
    agy launch [context folder] -- <antigravity command>
                                        Launch Antigravity CLI. Instead use 'agy' command if ${AISTACK_ANTIGRAVITY_LAUNCHER_HOME} is in your PATH.
                                        Use 'aistack agy register <shell>' to set it in your PATH.
    ----
    asm : Agent Skill Manager - https://github.com/luongnv89/asm
    asm install [@version]                Install and configure asm.
    asm uninstall                         Uninstall asm and unregister asm PATH.
    asm configure                         Configure asm with some default values. But do not fully reset all other existing config values. ('aistack asm install' include configuration)
    asm show-config                       Show current asm configuration.
    asm reset                             Reset asm configuration.
    asm register <all|shell|vs>           Register asm PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs").
    asm unregister [<all|shell|vs>]       Unregister asm PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs"). Default value is "all".
    asm launch [context folder] -- <asm command>
                                          Launch asm. Instead use 'asm' command if ${AISTACK_ASM_LAUNCHER_HOME} is in your PATH.
                                          Use 'aistack asm register <shell>' to set it in your PATH.
    ----
	BMAD-Method - https://docs.bmad-method.org/
    bmad <install|uninstall>            Install/Uninstall bmad cli.
    bmad register <all|shell|vs>        Register bmad cli PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs").
    bmad unregister [<all|shell|vs>]    Unregister bmad cli PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs"). Default value is "all".
    bmad launch -- <bmad command>       Launch bmad cli. (i.e: aistack bmad launch -- --help)
                                        Instead use 'bmad' or 'bmad-method' command if ${AISTACK_BMAD_LAUNCHER_HOME} is in your PATH.
                                        Use 'aistack bmad register <shell>' to set it in your PATH.
    ----
	gsd - Git. Shio. Done. - https://opengsd.net/ https://github.com/open-gsd/gsd-core
	gsd install [<any gsd option>]        Install GSD ('aistack gsd install --local')
    gsd uninstall [<any gsd option>]      Uinstall GSD ('aistack gsd uninstall --local')
    gsd help                              Show GSD help for options
    ----
    Agent Development Kit (ADK) - (https://adk.dev/)
    adk <install|uninstall>             Install/Uninstall the adk for python.
    adk register <all|shell|vs>         Register adk PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs").
    adk unregister [<all|shell|vs>]     Unregister adk PATH into shell env PATH ("all" supported shells or "bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs"). Default value is "all".
    adk launch -- <adk command>         Launch adk. (i.e: aistack adk launch -- --help)
                                        Instead use 'adk' command if ${AISTACK_ADK_LAUNCHER_HOME} is in your PATH.
                                        Use 'aistack adk register <shell>' to set it in your PATH.
    ----
    vs info                             Print VS Code informations.
    vs show-config                      Show current VS Code configuration.
    vs install|uninstall <extension id> Install/uninstall a VS Code extension from marketplace into current VS Code session.
    vs set <key> <value>                Set a VS Code configuration in settings file.
    vs del <key>                        Delete a VS Code configuration in settings file.
   	----
	nvm|npm|npx|bun|pip|pipx|uv [<command>]           Execute nvm, npm, npx, bun, pip, pipx, or uv command using the internal nodejs or python runtime from aistack. (i.e: aistack npm install -g typescript)
    ----
    app killport <port>                  Kill process running on a specific port.
    ----
EOF
}


# Main function
main() {
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        usage
        exit 0
    fi

    if [ "$#" -eq 0 ]; then
        usage
        exit 1
    fi

    local command="$1"
    shift
    case "$command" in
        help)
            usage
            exit 0
            ;;
        shell)
            $STELLA_API boot_app_shell "local"
			exit 0
            ;;
        info)
            aistack_info
			exit 0
            ;;
        init)
			# NOTE : aistack_install uninstall everything
            aistack_install

            aistack_initialize
            aistack_runtime_detect
            aistack_module_detect
		    aistack_run_context_file_generate
            aistack_tool_detect
            aistack_mcp_detect
            aistack_launcher_regenerate
			exit 0
            ;;
        uninstall)
            aistack_uninstall

            aistack_initialize
            aistack_runtime_detect
			aistack_module_detect
            aistack_run_context_file_generate
            aistack_tool_detect
            aistack_mcp_detect
            aistack_launcher_regenerate
			exit 0
            ;;
	esac


	# next commands requires core components installed
	aistack_component_core_is_detected



	case "$command" in
        bun)
            if ! aistack_runtime_is_detected "bun"; then echo " -- ERROR : bun managed runtime missing, use aistack runtime command"; exit 1; fi;     
			PATH="${AISTACK_RUNTIME_BUN_SEARCH_PATH}:${STELLA_ORIGINAL_SYSTEM_PATH}" "$command" "$@"
            ;;
        npm|npx)
            if ! aistack_runtime_is_detected "nodejs"; then echo " -- ERROR : nodejs managed runtime missing, use aistack runtime command"; exit 1; fi;     
			PATH="${AISTACK_RUNTIME_NODEJS_SEARCH_PATH}:${STELLA_ORIGINAL_SYSTEM_PATH}" "$command" "$@"
            ;;
        nvm)
            if ! aistack_runtime_is_detected "nodejs"; then echo " -- ERROR : nodejs managed runtime missing, use aistack runtime command"; exit 1; fi;     
            if [ "${AISTACK_MODULE_NVM_AVAILABLE}" = "true" ]; then
                "${command}" "$@"
            else
                echo " -- WARN : $command not found - reinstall nodejs managed runtime."
                exit 1
            fi
            ;;
        pip|pipx|uv)
            if ! aistack_runtime_is_detected "python"; then echo " -- ERROR : python managed runtime missing, use aistack runtime command"; exit 1; fi;     
            PATH="${AISTACK_RUNTIME_PYTHON_SEARCH_PATH}:${STELLA_ORIGINAL_SYSTEM_PATH}" "$command" "$@"
            ;;
		runtime)
			local sub_command="$1"
			shift
            case "${sub_command}" in
                add)
					aistack_runtime_install "$1"
					aistack_runtime_detect
					aistack_run_context_file_generate
				;;
				remove)
					aistack_runtime_uninstall "$1"
					aistack_runtime_detect
					aistack_run_context_file_generate
				;;
				*)
					echo "ERROR: Unknown command ${sub_command} for runtime"
					usage
					exit 1
				;;
			esac
			;;
        app)
            local sub_command="$1"
            shift
            case "${sub_command}" in
                killport)
                    local port="$1"
                    shift
                    if [ -z "$port" ]; then
                        echo " -- ERROR : Missing port for app killport"
                        usage
                        exit 1
                    fi
                    process_kill_by_port "$port"
                    ;;
                *)
                    echo "ERROR: Unknown command ${sub_command} for app"
                    usage
                    exit 1
                    ;;
            esac
            ;;
        oc)
            . "${_CURRENT_FILE_DIR}/lib/main_oc.sh"
            ;;
        gc)
            . "${_CURRENT_FILE_DIR}/lib/main_gc.sh"
            ;;
        cpa)
            . "${_CURRENT_FILE_DIR}/lib/main_cpa.sh"
            ;;
        agy)
            . "${_CURRENT_FILE_DIR}/lib/main_agy.sh"
            ;;
        vs)
            . "${_CURRENT_FILE_DIR}/lib/main_vs.sh"
            ;;
        orla)
            . "${_CURRENT_FILE_DIR}/lib/main_orla.sh"
            ;;
        bmad)
            . "${_CURRENT_FILE_DIR}/lib/main_bmad.sh"
            ;;
		gsd)
            . "${_CURRENT_FILE_DIR}/lib/main_gsd.sh"
            ;;
        adk)
            . "${_CURRENT_FILE_DIR}/lib/main_adk.sh"
            ;;
        kc)
            . "${_CURRENT_FILE_DIR}/lib/main_kilo.sh"
            ;;
        asm)
            . "${_CURRENT_FILE_DIR}/lib/main_asm.sh"
            ;;
        *)
            echo "ERROR: Unknown command $command"
            usage
            exit 1
            ;;
    esac

    
}

aistack_initialize

aistack_runtime_detect
aistack_module_detect

aistack_run_context_file_generate

aistack_tool_detect
aistack_mcp_detect
aistack_launcher_regenerate

main "$@"
