[STELLA]
APP_NAME=aistack-cli
APP_WORK_ROOT=workspace
APP_CACHE_DIR=cache
# stella feature list used accross aistack-cli as components
APP_FEATURE_LIST=yq#^4 jq#^1_8 miniforge3

[AISTACK]
# add search path of runtimes and modules to tool run context
TOOL_RUN_CONTEXT_ADD_RUNTIME=nodejs bun python
TOOL_RUN_CONTEXT_ADD_MODULE=yq jq
